name: Deploy Static Site

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  build:
    name: Build & Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      deploy: true
